import type { Champion } from "./types"

export const sampleChampions: Omit<Champion, "id">[] = [
  // 거점리더 등급
  {
    name: "김정수",
    organization: "행정안전부 디지털정부국",
    role: "디지털정부국장",
    grade: "거점리더",
    message: "AI 기술로 국민 모두가 편리한 디지털 정부를 만들어가겠습니다.",
    specialties: ["디지털정부정책", "AI거버넌스", "데이터정책", "스마트시티"],
    profileImage: "/profiles/kim-jeong-su.png",
  },
  {
    name: "박민영",
    organization: "행정안전부 정보화전략실",
    role: "정보화전략실장",
    grade: "거점리더",
    message: "데이터 기반 행정혁신으로 국민 서비스 품질을 높이겠습니다.",
    specialties: ["정보화전략", "빅데이터", "클라우드", "사이버보안"],
    profileImage: "/profiles/park-min-young.png",
  },
  {
    name: "이승호",
    organization: "행정안전부 혁신기획관",
    role: "혁신기획관",
    grade: "거점리더",
    message: "AI를 활용한 행정혁신으로 더 나은 미래를 설계하겠습니다.",
    specialties: ["행정혁신", "AI정책", "디지털전환", "공공서비스"],
    profileImage: "/profiles/lee-seung-ho.png",
  },

  // 블랙 등급
  {
    name: "최현우",
    organization: "행정안전부 AI정책팀",
    role: "AI정책팀장",
    grade: "블랙",
    message: "AI 윤리와 안전을 바탕으로 신뢰할 수 있는 AI 생태계를 구축하겠습니다.",
    specialties: ["AI정책", "머신러닝", "AI윤리", "알고리즘"],
    profileImage: "/profiles/choi-hyun-woo.png",
  },
  {
    name: "정수연",
    organization: "행정안전부 데이터분석팀",
    role: "데이터분석팀장",
    grade: "블랙",
    message: "빅데이터 분석으로 정책 의사결정을 지원하겠습니다.",
    specialties: ["빅데이터", "데이터분석", "통계모델링", "예측분석"],
    profileImage: "/profiles/jung-su-yeon.png",
  },
  {
    name: "강태민",
    organization: "행정안전부 스마트정부팀",
    role: "스마트정부팀장",
    grade: "블랙",
    message: "스마트 기술로 효율적이고 투명한 정부를 만들어가겠습니다.",
    specialties: ["스마트정부", "IoT", "블록체인", "디지털트윈"],
    profileImage: "/profiles/kang-tae-min.png",
  },
  {
    name: "윤지혜",
    organization: "행정안전부 사이버보안팀",
    role: "사이버보안팀장",
    grade: "블랙",
    message: "AI 기반 보안 시스템으로 안전한 디지털 환경을 구축하겠습니다.",
    specialties: ["사이버보안", "AI보안", "위협탐지", "보안정책"],
    profileImage: "/profiles/yoon-ji-hye.png",
  },

  // 블루 등급
  {
    name: "김도현",
    organization: "행정안전부 AI개발팀",
    role: "AI개발 선임연구원",
    grade: "블루",
    message: "실용적인 AI 솔루션으로 국민 편의를 증진시키겠습니다.",
    specialties: ["딥러닝", "자연어처리", "컴퓨터비전", "AI모델링"],
    profileImage: "/profiles/kim-do-hyun.png",
  },
  {
    name: "이소영",
    organization: "행정안전부 데이터팀",
    role: "데이터 사이언티스트",
    grade: "블루",
    message: "데이터의 가치를 발견하여 정책 혁신에 기여하겠습니다.",
    specialties: ["데이터사이언스", "파이썬", "R", "시각화"],
    profileImage: "/profiles/lee-so-young.png",
  },
  {
    name: "박준혁",
    organization: "행정안전부 플랫폼팀",
    role: "플랫폼 아키텍트",
    grade: "블루",
    message: "안정적이고 확장 가능한 AI 플랫폼을 구축하겠습니다.",
    specialties: ["클라우드아키텍처", "마이크로서비스", "DevOps", "쿠버네티스"],
    profileImage: "/profiles/park-jun-hyuk.png",
  },
  {
    name: "조민서",
    organization: "행정안전부 UX팀",
    role: "UX 디자이너",
    grade: "블루",
    message: "사용자 중심의 AI 서비스 경험을 설계하겠습니다.",
    specialties: ["UX디자인", "사용자연구", "프로토타이핑", "인터랙션디자인"],
    profileImage: "/profiles/jo-min-seo.png",
  },
  {
    name: "한상민",
    organization: "행정안전부 품질관리팀",
    role: "AI 품질관리 전문가",
    grade: "블루",
    message: "AI 모델의 품질과 신뢰성을 보장하겠습니다.",
    specialties: ["모델검증", "품질관리", "테스트자동화", "성능최적화"],
    profileImage: "/profiles/han-sang-min.png",
  },

  // 그린 등급
  {
    name: "신예린",
    organization: "행정안전부 AI연구팀",
    role: "AI 연구원",
    grade: "그린",
    message: "새로운 AI 기술 연구로 혁신의 씨앗을 키우겠습니다.",
    specialties: ["머신러닝", "파이썬", "텐서플로우", "연구개발"],
    profileImage: "/profiles/shin-ye-rin.png",
  },
  {
    name: "오태준",
    organization: "행정안전부 개발팀",
    role: "주니어 개발자",
    grade: "그린",
    message: "열정과 창의로 AI 서비스 개발에 기여하겠습니다.",
    specialties: ["웹개발", "자바스크립트", "리액트", "API개발"],
    profileImage: "/profiles/oh-tae-jun.png",
  },
  {
    name: "김하은",
    organization: "행정안전부 분석팀",
    role: "데이터 분석가",
    grade: "그린",
    message: "데이터 분석을 통해 인사이트를 발굴하겠습니다.",
    specialties: ["데이터분석", "SQL", "엑셀", "통계분석"],
    profileImage: "/profiles/kim-ha-eun.png",
  },
  {
    name: "이준호",
    organization: "행정안전부 기획팀",
    role: "정책 기획자",
    grade: "그린",
    message: "AI 정책 기획으로 디지털 정부 발전에 기여하겠습니다.",
    specialties: ["정책기획", "프로젝트관리", "업무분석", "문서작성"],
    profileImage: "/profiles/lee-jun-ho.png",
  },
  {
    name: "정다은",
    organization: "행정안전부 지원팀",
    role: "AI 운영 담당자",
    grade: "그린",
    message: "AI 시스템 운영으로 안정적인 서비스를 제공하겠습니다.",
    specialties: ["시스템운영", "모니터링", "장애대응", "사용자지원"],
    profileImage: "/profiles/jung-da-eun.png",
  },
  {
    name: "최민재",
    organization: "행정안전부 교육팀",
    role: "AI 교육 담당자",
    grade: "그린",
    message: "AI 교육을 통해 디지털 역량 강화에 기여하겠습니다.",
    specialties: ["교육기획", "콘텐츠개발", "강의", "역량평가"],
    profileImage: "/profiles/choi-min-jae.png",
  },
]
